### ISSUE TITLE
Campo com visibility function não é mostrado após carregamento

### ISSUE THREAD

**Issue by DenilsonMVS** [synergia-labs/MeteorReactBaseMUI#17]
# Como replicar:

### No módulo de exemplo, adicione o seguinte campo no esquema:

``` typescript
  justification: {
    type: String,
    label: 'Justificativa',
    optional: false,
    defaultValue: '',
    visibilityFunction: (doc) => {
      return doc?.typeMulti === 'alta' || false;
    },
  },
```

Isso criará um novo campo que apenas será mostrado se a prioridade for alta.

### No arquivo exampleServerApi.ts, altere a publicação de exampleDetail:

``` typescript
this.addPublication('exampleDetail', (filter = {}) => {
  return this.defaultDetailCollectionPublication(filter, {
    projection: {
      contacts: 1,
      title: 1,
      description: 1,
      type: 1,
      typeMulti: 1,
      date: 1,
      files: 1,
      chip: 1,
      statusRadio: 1,
      statusToggle: 1,
      slider: 1,
      check: 1,
      address: 1,
      justification: 1,
    }
  });
});
```

### Adicione um textField em exampleDetailView.tsx:

``` TSX
<ExampleDetailStyles.body>
  <ExampleDetailStyles.formColumn>
    <SysTextField name="title" placeholder="Ex.: Item XX" />
    <SysSelectField name="type" placeholder="Selecionar" />
    <SysRadioButton name="typeMulti" alignment="row" size="small" />
    <SysTextField name="justification" />
    <SysTextField
      name="description"
      placeholder="Acrescente informações sobre o item (3 linhas)"
      multiline
      rows={3}
      showNumberCharactersTyped
      max={200}
    />
    <SysUploadFile name="files" />
    <SysSlider name="slider" />
    <SysLocationField name="address" />
  </ExampleDetailStyles.formColumn>
  <ExampleDetailStyles.formColumn>
    <SysCheckBox name="check" alignment="row" />
  </ExampleDetailStyles.formColumn>
</ExampleDetailStyles.body>
```

Cadadastre um novo documento com prioridade alta e com uma justificativa. 

![Screenshot from 2024-04-29 15-42-33](https://github.com/synergia-labs/MeteorReactBaseMUI/assets/72045275/6cf31a17-5c6a-4bed-90e4-ec8fa142e327)

Volte para a lista de exemplos. Clique no exemplo cadastrado. O campo justificativa não é mostrado.

![Screenshot from 2024-04-29 15-42-47](https://github.com/synergia-labs/MeteorReactBaseMUI/assets/72045275/37142555-4ac5-49b8-b47f-45fae3ef2375)

# Como resolver:

No arquivo sysForm.tsx, adicione checkVisibilityFields() no useEffect que é chamado na modificação do documento:

``` TSX
useEffect(() => {
  updateValue(doc);
  refDoc.current = doc;
  checkVisibilityFields();
}, [doc]);
```

**Comment by Gustavo01rb** [comment]
Obrigado pela contribuição! Aprecio o detalhamento do problema e a solução proposta. Se precisar de mais alguma coisa ou tiver outras sugestões, estou à disposição para continuar colaborando
