### ISSUE TITLE
SysDatePickerField não mostra a data em modo de leitura

### ISSUE THREAD

**Issue by DenilsonMVS** [synergia-labs/MeteorReactBaseMUI#18]
# Como replicar

Adicione um SysDatePickerField em exampleDetailView.tsx:

``` TSX
<ExampleDetailStyles.formColumn>
  <SysTextField name="title" placeholder="Ex.: Item XX" />
  <SysSelectField name="type" placeholder="Selecionar" />
  <SysRadioButton name="typeMulti" alignment="row" size="small" />
  <SysDatePickerField name="date" />
  <SysTextField
    name="description"
    placeholder="Acrescente informações sobre o item (3 linhas)"
    multiline
    rows={3}
    showNumberCharactersTyped
    max={200}
  />
  <SysUploadFile name="files" />
  <SysSlider name="slider" />
  <SysLocationField name="address" />
</ExampleDetailStyles.formColumn>
```

Cadastre uma data:

![Screenshot from 2024-04-29 15-52-47](https://github.com/synergia-labs/MeteorReactBaseMUI/assets/72045275/d3e77b3e-cdf3-4100-89bc-bbfc2e1f30bb)

A data não é mostrada em modo de leitura:

![Screenshot from 2024-04-29 15-52-58](https://github.com/synergia-labs/MeteorReactBaseMUI/assets/72045275/7e66432b-7f5b-40bf-af36-9e9db98769b1)

# Possível resolução

Alterar em sysDatePickerField.tsx:

``` TSX
if (readOnly)
  return <SysViewField label={label} placeholder={typeof dateValue != 'string' ? '-' : dateValue || '-'} />;
```

Para:

``` TSX
if (readOnly)
  return <SysViewField label={label} placeholder={dateValue instanceof Date ? formatDate(dateValue) : dateValue} />;
```

**Comment by Gustavo01rb** [comment]
Oi Denilson! Agradeço muito pelas contribuições. Estou totalmente de acordo com os pontos que você apresentou. Assim que você criar um PR, farei questão de adicionar suas mudanças.

Se surgir qualquer dúvida, por favor, não hesite em me chamar. Estou à disposição para esclarecer qualquer questão que possa surgir durante o processo.
